function dispCorrelationsCAMELS(data_CAMELS,attribute,attribute_str,...
    catchments,additional_attributes)
%dispCorrelationsCAMELS displays correlations with all CAMELS attributes
%   % some things are missing (e.g. non-numeric data, hydr. signatures,
%   etc.)
%   Skip metadata, non-numeric attributes, hydrological signatures
%   (since we are interested in catchment attributes), etc...
%
%   INPUT
%   Q: CAMELS data
%   attribute: attribute
%   attribute_str: name of attribute
%   catchments: list with catchment vector indices
%   additional_attributes: additional attributes
%
%   OUTPUT
%   displays text
%
%   ---
%
%   Sebastian Gnann, sebastian.gnann@bristol.ac.uk (2020)

% topo
fprintf('\n%s Pearson Spearman\n---\n', attribute_str)
fprintf('elev_mean %.2f %.2f \n',...
    (corr(data_CAMELS.elev_mean(catchments),attribute(catchments),'rows','complete')),...
    (corr(data_CAMELS.elev_mean(catchments),attribute(catchments),'rows','complete','type','Spearman')))
fprintf('slope_mean %.2f %.2f \n',...
    (corr(data_CAMELS.slope_mean(catchments),attribute(catchments),'rows','complete')),...
    (corr(data_CAMELS.slope_mean(catchments),attribute(catchments),'rows','complete','type','Spearman')))
fprintf('area_gages2 %.2f %.2f \n',...
    (corr(data_CAMELS.area_gages2(catchments),attribute(catchments),'rows','complete')),...
    (corr(data_CAMELS.area_gages2(catchments),attribute(catchments),'rows','complete','type','Spearman')))
fprintf('area_geospa_fabric %.2f %.2f \n',...
    (corr(data_CAMELS.area_geospa_fabric(catchments),attribute(catchments),'rows','complete')),...
    (corr(data_CAMELS.area_geospa_fabric(catchments),attribute(catchments),'rows','complete','type','Spearman')))

% climate
fprintf('p_mean %.2f %.2f \n',...
    (corr(data_CAMELS.p_mean(catchments),attribute(catchments),'rows','complete')),...
    (corr(data_CAMELS.p_mean(catchments),attribute(catchments),'rows','complete','type','Spearman')))
fprintf('pet_mean %.2f %.2f \n',...
    (corr(data_CAMELS.pet_mean(catchments),attribute(catchments),'rows','complete')),...
    (corr(data_CAMELS.pet_mean(catchments),attribute(catchments),'rows','complete','type','Spearman')))
fprintf('aridity %.2f %.2f \n',...
    (corr(data_CAMELS.aridity(catchments),attribute(catchments),'rows','complete')),...
    (corr(data_CAMELS.aridity(catchments),attribute(catchments),'rows','complete','type','Spearman')))
fprintf('p_seasonality %.2f %.2f \n',...
    (corr(data_CAMELS.p_seasonality(catchments),attribute(catchments),'rows','complete')),...
    (corr(data_CAMELS.p_seasonality(catchments),attribute(catchments),'rows','complete','type','Spearman')))
fprintf('frac_snow %.2f %.2f \n',...
    (corr(data_CAMELS.frac_snow(catchments),attribute(catchments),'rows','complete')),...
    (corr(data_CAMELS.frac_snow(catchments),attribute(catchments),'rows','complete','type','Spearman')))
fprintf('high_prec_freq %.2f %.2f \n',...
    (corr(data_CAMELS.high_prec_freq(catchments),attribute(catchments),'rows','complete')),...
    (corr(data_CAMELS.high_prec_freq(catchments),attribute(catchments),'rows','complete','type','Spearman')))
fprintf('high_prec_dur %.2f %.2f \n',...
    (corr(data_CAMELS.high_prec_dur(catchments),attribute(catchments),'rows','complete')),...
    (corr(data_CAMELS.high_prec_dur(catchments),attribute(catchments),'rows','complete','type','Spearman')))
% fprintf('high_prec_timing %.2f %.2f \n',...
%     (corr(data_CAMELS.high_prec_timing(catchments),attribute(catchments),'rows','complete')),...
%     (corr(data_CAMELS.high_prec_timing(catchments),attribute(catchments),'rows','complete','type','Spearman')))
fprintf('low_prec_freq %.2f %.2f \n',...
    (corr(data_CAMELS.low_prec_freq(catchments),attribute(catchments),'rows','complete')),...
    (corr(data_CAMELS.low_prec_freq(catchments),attribute(catchments),'rows','complete','type','Spearman')))
fprintf('low_prec_dur %.2f %.2f \n',...
    (corr(data_CAMELS.low_prec_dur(catchments),attribute(catchments),'rows','complete')),...
    (corr(data_CAMELS.low_prec_dur(catchments),attribute(catchments),'rows','complete','type','Spearman')))
% fprintf('low_prec_timing %.2f %.2f \n',...
%     (corr(data_CAMELS.low_prec_timing(catchments),attribute(catchments),'rows','complete')),...
%     (corr(data_CAMELS.low_prec_timing(catchments),attribute(catchments),'rows','complete','type','Spearman')))

% hydro
% fprintf('q_mean %.2f %.2f \n',...
%     (corr(data_CAMELS.q_mean(catchments),attribute(catchments),'rows','complete')),...
%     (corr(data_CAMELS.q_mean(catchments),attribute(catchments),'rows','complete','type','Spearman')))
% fprintf('runoff_ratio %.2f %.2f \n',...
%     (corr(data_CAMELS.runoff_ratio(catchments),attribute(catchments),'rows','complete')),...
%     (corr(data_CAMELS.runoff_ratio(catchments),attribute(catchments),'rows','complete','type','Spearman')))

% vege
fprintf('frac_forest %.2f %.2f \n',...
    (corr(data_CAMELS.frac_forest(catchments),attribute(catchments),'rows','complete')),...
    (corr(data_CAMELS.frac_forest(catchments),attribute(catchments),'rows','complete','type','Spearman')))
fprintf('lai_max %.2f %.2f \n',...
    (corr(data_CAMELS.lai_max(catchments),attribute(catchments),'rows','complete')),...
    (corr(data_CAMELS.lai_max(catchments),attribute(catchments),'rows','complete','type','Spearman')))
fprintf('lai_diff %.2f %.2f \n',...
    (corr(data_CAMELS.lai_diff(catchments),attribute(catchments),'rows','complete')),...
    (corr(data_CAMELS.lai_diff(catchments),attribute(catchments),'rows','complete','type','Spearman')))
fprintf('gvf_max %.2f %.2f \n',...
    (corr(data_CAMELS.gvf_max(catchments),attribute(catchments),'rows','complete')),...
    (corr(data_CAMELS.gvf_max(catchments),attribute(catchments),'rows','complete','type','Spearman')))
fprintf('gvf_diff %.2f %.2f \n',...
    (corr(data_CAMELS.gvf_diff(catchments),attribute(catchments),'rows','complete')),...
    (corr(data_CAMELS.gvf_diff(catchments),attribute(catchments),'rows','complete','type','Spearman')))
fprintf('root_depth_50 %.2f %.2f \n',...
    (corr(data_CAMELS.root_depth_50(catchments),attribute(catchments),'rows','complete')),...
    (corr(data_CAMELS.root_depth_50(catchments),attribute(catchments),'rows','complete','type','Spearman')))
fprintf('root_depth_99 %.2f %.2f \n',...
    (corr(data_CAMELS.root_depth_99(catchments),attribute(catchments),'rows','complete')),...
    (corr(data_CAMELS.root_depth_99(catchments),attribute(catchments),'rows','complete','type','Spearman')))

% soil
fprintf('soil_depth_pelletier %.2f %.2f \n',...
    (corr(data_CAMELS.soil_depth_pelletier(catchments),attribute(catchments),'rows','complete')),...
    (corr(data_CAMELS.soil_depth_pelletier(catchments),attribute(catchments),'rows','complete','type','Spearman')))
fprintf('soil_depth_statsgo %.2f %.2f \n',...
    (corr(data_CAMELS.soil_depth_statsgo(catchments),attribute(catchments),'rows','complete')),...
    (corr(data_CAMELS.soil_depth_statsgo(catchments),attribute(catchments),'rows','complete','type','Spearman')))
fprintf('soil_porosity %.2f %.2f \n',...
    (corr(data_CAMELS.soil_porosity(catchments),attribute(catchments),'rows','complete')),...
    (corr(data_CAMELS.soil_porosity(catchments),attribute(catchments),'rows','complete','type','Spearman')))
fprintf('soil_conductivity %.2f %.2f \n',...
    (corr(data_CAMELS.soil_conductivity(catchments),attribute(catchments),'rows','complete')),...
    (corr(data_CAMELS.soil_conductivity(catchments),attribute(catchments),'rows','complete','type','Spearman')))
fprintf('max_water_content %.2f %.2f \n',...
    (corr(data_CAMELS.max_water_content(catchments),attribute(catchments),'rows','complete')),...
    (corr(data_CAMELS.max_water_content(catchments),attribute(catchments),'rows','complete','type','Spearman')))
fprintf('sand_frac %.2f %.2f \n',...
    (corr(data_CAMELS.sand_frac(catchments),attribute(catchments),'rows','complete')),...
    (corr(data_CAMELS.sand_frac(catchments),attribute(catchments),'rows','complete','type','Spearman')))
fprintf('silt_frac %.2f %.2f \n',...
    (corr(data_CAMELS.silt_frac(catchments),attribute(catchments),'rows','complete')),...
    (corr(data_CAMELS.silt_frac(catchments),attribute(catchments),'rows','complete','type','Spearman')))
fprintf('clay_frac %.2f %.2f \n',...
    (corr(data_CAMELS.clay_frac(catchments),attribute(catchments),'rows','complete')),...
    (corr(data_CAMELS.clay_frac(catchments),attribute(catchments),'rows','complete','type','Spearman')))
fprintf('water_frac %.2f %.2f \n',...
    (corr(data_CAMELS.water_frac(catchments),attribute(catchments),'rows','complete')),...
    (corr(data_CAMELS.water_frac(catchments),attribute(catchments),'rows','complete','type','Spearman')))
fprintf('organic_frac %.2f %.2f \n',...
    (corr(data_CAMELS.organic_frac(catchments),attribute(catchments),'rows','complete')),...
    (corr(data_CAMELS.organic_frac(catchments),attribute(catchments),'rows','complete','type','Spearman')))
fprintf('other_frac %.2f %.2f \n',...
    (corr(data_CAMELS.other_frac(catchments),attribute(catchments),'rows','complete')),...
    (corr(data_CAMELS.other_frac(catchments),attribute(catchments),'rows','complete','type','Spearman')))

% geo
fprintf('carb_rock_frac %.2f %.2f \n',...
    (corr(data_CAMELS.carbonate_rocks_frac(catchments),attribute(catchments),'rows','complete')),...
    (corr(data_CAMELS.carbonate_rocks_frac(catchments),attribute(catchments),'rows','complete','type','Spearman')))
fprintf('geol_permeability %.2f %.2f \n',...
    (corr(data_CAMELS.geol_permeability(catchments),attribute(catchments),'rows','complete')),...
    (corr(data_CAMELS.geol_permeability(catchments),attribute(catchments),'rows','complete','type','Spearman')))
fprintf('geol_porosity %.2f %.2f \n',...
    (corr(data_CAMELS.geol_porosity(catchments),attribute(catchments),'rows','complete')),...
    (corr(data_CAMELS.geol_porosity(catchments),attribute(catchments),'rows','complete','type','Spearman')))

% additional attributes
for i = 1:size(additional_attributes,2)
    fprintf('additional%.0f %.2f %.2f \n',i,...
        (corr(additional_attributes(catchments,i),attribute(catchments),'rows','complete')),...
        (corr(additional_attributes(catchments,i),attribute(catchments),'rows','complete','type','Spearman')))
    
end

end