function [] = plotCatchmentAttributes(data_CAMELS,signatures_CAMELS,relief,i)
%plotCatchmentAttributesNew Plots scatter plot of two variables.
% Optional:
%   - ...
%
% INPUT
%   catchment_data: structure with CAMELS data
%   signatures_CAMELS: a structure with CAMELS signatures
%   relief: additional catchment attribute [m]
%   i: Matlab index of catchment
%
%   OUTPUT
%   plot
%
%   ---
%
%   Sebastian Gnann, sebastian.gnann@bristol.ac.uk (2020)

% check input parameters
if nargin < 2
    error('Not enough input arguments.')
end

%% extract data
t = datetime(data_CAMELS.P{i}(:,1),'ConvertFrom','datenum');
P = data_CAMELS.P{i}(:,2);
PET = data_CAMELS.PET{i}(:,2);
Q = data_CAMELS.Q{i}(:,2);
ID = data_CAMELS.gauge_id(i);

%% catchment info
% dim =  [0.533 0.170 0.100 0.395];
% dim =  [0.771 0.139 0.200 0.386];
dim =  [0.772 0.400 0.223 0.290];
%     '\n','Index: ', num2str(i),... 
%    'ID: ', num2str(ID),...
% str = sprintf([...
%     'PET/P [-]: ', num2str(round(data_CAMELS.aridity(i),2)),...
%     '\n','fsnow [-]: ', num2str(round(data_CAMELS.frac_snow(i),2)),...
%     '\n','Q/P [-]: ', num2str(round(data_CAMELS.runoff_ratio(i),2)),...
%     '\n','BFI{5} [-]: ', num2str(round(signatures_CAMELS.BFI5(i),2)),...
%     '\n','BFI{90} [-]: ', num2str(round(signatures_CAMELS.BFI90(i),2)),...
%     '\n','\\betam [-]: ', num2str(round(signatures_CAMELS.recession_beta(i),2))]);
str = sprintf([...
    '\n','BFI_{5} [-]: ', num2str(round(signatures_CAMELS.BFI5(i),2)),...
    '\n','BFI_{90} [-]: ', num2str(round(signatures_CAMELS.BFI90(i),2)),...
    '\n','\\beta_m [-]: ', num2str(round(signatures_CAMELS.recession_beta(i),2))]);
annotation('textbox',dim,'String',str,'FitBoxToText','on',...
    'FontSize',7,'EdgeColor','None');

% display info
fprintf([...
    'ID: ', num2str(ID),...
    '\n','Index: ', num2str(i),...
    '\n','PET/P [-]: ', num2str(round(data_CAMELS.aridity(i),2)),...
    '\n','P [-]: ', num2str(round(data_CAMELS.p_mean(i),2)),...
    '\n','PET [-]: ', num2str(round(data_CAMELS.pet_mean(i),2)),...
    '\n','Q/P [-]: ', num2str(round(data_CAMELS.runoff_ratio(i),2)),...
    '\n','Qf/P [-]: ', num2str(round((1-signatures_CAMELS.BFI5(i))*data_CAMELS.runoff_ratio(i),2)),...
    '\n','Qb5/P [-]: ', num2str(round((signatures_CAMELS.BFI5(i)-signatures_CAMELS.BFI90(i))*data_CAMELS.runoff_ratio(i),2)),...
    '\n','Qb90/P [-]: ', num2str(round(signatures_CAMELS.BFI90(i)*data_CAMELS.runoff_ratio(i),2)),...
    '\n','E/P [-]: ', num2str(round(1-data_CAMELS.runoff_ratio(i),2)),...
    '\n','f_s[-]: ', num2str(round(data_CAMELS.frac_snow(i),2)),...
    '\n','Slope [m/km]: ', num2str(round(data_CAMELS.slope_mean(i),0)),...
    '\n','Relief [m]: ', num2str(round(relief(i),0)),'\n\n']);

end
